import {
  Currency,
  EntryType,
  PrismaClient,
  Status,
  TransactionType,
} from 'prisma/generated/prisma/client';

export const seedTransactions = async (prisma: PrismaClient) => {
  console.log('  ➤ Seeding transactions...');

  const ledger = await prisma.ledger.findFirst({
    where: { name: 'Home Budget' },
    include: {
      categories: true,
      paymentMethods: { include: { paymentMethod: true } },
    },
  });

  if (!ledger) {
    console.warn('  ⚠ Ledger not found, skipping transactions.');
    return;
  }
  const user = await prisma.user.findUnique({
    where: { id: ledger.ownerId },
    include: { paymentMethods: true },
  });

  if (!user) {
    console.warn('  ⚠ User not found, skipping transactions.');
    return;
  }

  // ─── Helpers ────────────────────────────────────────────────────────────────

  const cat = (name: string) => {
    const found = ledger.categories.find((c) => c.name === name);
    if (!found) throw new Error(`Category not found: ${name}`);
    return found.id;
  };

  const pm = (name: string) => {
    const found = user.paymentMethods.find((p) => p.name === name);
    if (!found) throw new Error(`Payment method not found: ${name}`);
    return found.id;
  };

  // Upsert groups on the fly and cache them
  const groupCache: Record<string, number> = {};
  const group = async (name: string): Promise<number> => {
    if (groupCache[name]) return groupCache[name];
    const user = await prisma.user.findUnique({
      where: { email: 'matias@mail.com' },
    });
    if (!user) throw new Error('User not found');
    const g = await prisma.group.upsert({
      where: { ledgerId_name: { ledgerId: ledger.id, name } },
      update: {},
      create: { name, ledgerId: ledger.id, userId: user.id },
    });
    groupCache[name] = g.id;
    return g.id;
  };

  const d = (dateStr: string): Date => {
    const [day, month, year] = dateStr.split('/').map(Number);
    return new Date(year < 100 ? 2000 + year : year, month - 1, day);
  };

  const paymentMonth = (monthStr: string): Date => {
    const months: Record<string, number> = {
      ene: 0,
      feb: 1,
      mar: 2,
      abr: 3,
      may: 4,
      jun: 5,
      jul: 6,
      ago: 7,
      sep: 8,
      oct: 9,
      nov: 10,
      dic: 11,
    };
    const [mon, yr] = monthStr.split('-');
    const year = 2000 + parseInt(yr);
    return new Date(year, months[mon], 1);
  };

  const amount = (str: string): number => {
    // "527.653.0" → 527653.0
    const cleaned = str.replace(/\./g, '').replace(',', '.');
    return parseFloat(cleaned);
  };

  // ─── Transaction definitions ─────────────────────────────────────────────────

  type TxDef = {
    entryType: EntryType;
    pmName: string;
    groupName: string;
    categoryName: string;
    comment: string;
    transactionDate: string;
    paymentMonthStr: string;
    installments: number;
    installment: number;
    totalAmount: number;
    transactionType?: TransactionType;
  };

  const txDefs: TxDef[] = [
    // ── SALARY (income) ──────────────────────────────────────────────────────
    {
      entryType: EntryType.INCOME,
      pmName: 'Salary',
      groupName: 'Salary',
      categoryName: 'Home Expenses',
      comment: 'Monthly salary',
      transactionDate: '1/12/25',
      paymentMonthStr: 'dic-25',
      installments: 1,
      installment: 1,
      totalAmount: 1500000,
      transactionType: TransactionType.FIXED,
    },
    {
      entryType: EntryType.INCOME,
      pmName: 'Salary',
      groupName: 'Salary',
      categoryName: 'Home Expenses',
      comment: 'Monthly salary',
      transactionDate: '1/1/26',
      paymentMonthStr: 'ene-26',
      installments: 1,
      installment: 1,
      totalAmount: 1500000,
      transactionType: TransactionType.FIXED,
    },
    {
      entryType: EntryType.INCOME,
      pmName: 'Salary',
      groupName: 'Salary',
      categoryName: 'Home Expenses',
      comment: 'Monthly salary',
      transactionDate: '1/2/26',
      paymentMonthStr: 'feb-26',
      installments: 1,
      installment: 1,
      totalAmount: 1500000,
      transactionType: TransactionType.FIXED,
    },

    // ── DECEMBER 2025 ────────────────────────────────────────────────────────
    {
      entryType: EntryType.EXPENSE,
      pmName: 'Cash / Transfer',
      groupName: 'Rent & Building Fees',
      categoryName: 'Home Expenses',
      comment: 'Alquiler',
      transactionDate: '1/12/25',
      paymentMonthStr: 'dic-25',
      installments: 1,
      installment: 1,
      totalAmount: 527653,
    },
    {
      entryType: EntryType.EXPENSE,
      pmName: 'Cash / Transfer',
      groupName: 'Rent & Building Fees',
      categoryName: 'Home Expenses',
      comment: 'Expensas',
      transactionDate: '1/12/25',
      paymentMonthStr: 'dic-25',
      installments: 1,
      installment: 1,
      totalAmount: 98439,
    },
    {
      entryType: EntryType.EXPENSE,
      pmName: 'Visa Galicia',
      groupName: 'Utilities Lavalle',
      categoryName: 'Home Expenses',
      comment: 'Cable/Internet',
      transactionDate: '1/12/25',
      paymentMonthStr: 'dic-25',
      installments: 1,
      installment: 1,
      totalAmount: 24666.8,
    },
    {
      entryType: EntryType.EXPENSE,
      pmName: 'Visa Galicia',
      groupName: 'Utilities Lavalle',
      categoryName: 'Home Expenses',
      comment: 'Edesur',
      transactionDate: '1/12/25',
      paymentMonthStr: 'dic-25',
      installments: 1,
      installment: 1,
      totalAmount: 26996,
    },
    {
      entryType: EntryType.EXPENSE,
      pmName: 'Visa Ciudad',
      groupName: 'Utilities Lavalle',
      categoryName: 'Home Expenses',
      comment: 'Metrogas',
      transactionDate: '1/12/25',
      paymentMonthStr: 'dic-25',
      installments: 1,
      installment: 1,
      totalAmount: 13225.5,
    },
    {
      entryType: EntryType.EXPENSE,
      pmName: 'Cash / Transfer',
      groupName: 'Utilities Lavalle',
      categoryName: 'Home Expenses',
      comment: 'ABL',
      transactionDate: '1/12/25',
      paymentMonthStr: 'dic-25',
      installments: 1,
      installment: 1,
      totalAmount: 19489,
    },
    {
      entryType: EntryType.EXPENSE,
      pmName: 'Cash / Transfer',
      groupName: 'Childcare',
      categoryName: 'Home Expenses',
      comment: 'Yamile',
      transactionDate: '1/12/25',
      paymentMonthStr: 'dic-25',
      installments: 1,
      installment: 1,
      totalAmount: 150000,
    },
    {
      entryType: EntryType.EXPENSE,
      pmName: 'Cash / Transfer',
      groupName: 'Childcare',
      categoryName: 'Home Expenses',
      comment: 'Yamile - Aguinaldo',
      transactionDate: '1/12/25',
      paymentMonthStr: 'dic-25',
      installments: 1,
      installment: 1,
      totalAmount: 156559,
    },
    {
      entryType: EntryType.EXPENSE,
      pmName: 'Visa Galicia',
      groupName: 'Childcare',
      categoryName: 'Home Expenses',
      comment: 'Yamile - Aportes',
      transactionDate: '1/12/25',
      paymentMonthStr: 'dic-25',
      installments: 1,
      installment: 1,
      totalAmount: 33756.2,
    },
    {
      entryType: EntryType.EXPENSE,
      pmName: 'Visa Galicia',
      groupName: 'Utilities',
      categoryName: 'Home Expenses',
      comment: 'Celular Mati',
      transactionDate: '1/12/25',
      paymentMonthStr: 'dic-25',
      installments: 1,
      installment: 1,
      totalAmount: 39933,
    },
    {
      entryType: EntryType.EXPENSE,
      pmName: 'Cash / Transfer',
      groupName: 'Liam Kindergarten',
      categoryName: 'Childcare',
      comment: 'Jardín Liam',
      transactionDate: '1/12/25',
      paymentMonthStr: 'dic-25',
      installments: 1,
      installment: 1,
      totalAmount: 388000,
    },
    {
      entryType: EntryType.EXPENSE,
      pmName: 'Visa Galicia',
      groupName: 'Noah Kindergarten',
      categoryName: 'Childcare',
      comment: 'Jardín Noah 11/25',
      transactionDate: '1/12/25',
      paymentMonthStr: 'dic-25',
      installments: 1,
      installment: 1,
      totalAmount: 171373.3,
    },
    {
      entryType: EntryType.EXPENSE,
      pmName: 'Cash / Transfer',
      groupName: 'Gifts',
      categoryName: 'Gifts',
      comment: 'Regalo Pablo',
      transactionDate: '1/12/25',
      paymentMonthStr: 'dic-25',
      installments: 1,
      installment: 1,
      totalAmount: 21000,
    },
    {
      entryType: EntryType.EXPENSE,
      pmName: 'Cash / Transfer',
      groupName: 'Noah Kindergarten',
      categoryName: 'Gifts',
      comment: 'Regalo compañeros',
      transactionDate: '1/12/25',
      paymentMonthStr: 'dic-25',
      installments: 1,
      installment: 1,
      totalAmount: 24000,
    },
    {
      entryType: EntryType.EXPENSE,
      pmName: 'Visa Galicia',
      groupName: 'Health Insurance',
      categoryName: 'Health',
      comment: 'OSDE 10/2025',
      transactionDate: '1/12/25',
      paymentMonthStr: 'dic-25',
      installments: 1,
      installment: 1,
      totalAmount: 338169.2,
    },
    {
      entryType: EntryType.EXPENSE,
      pmName: 'Cash / Transfer',
      groupName: 'Taxis & Rideshare',
      categoryName: 'Transport',
      comment: 'Sube',
      transactionDate: '1/12/25',
      paymentMonthStr: 'dic-25',
      installments: 1,
      installment: 1,
      totalAmount: 48000,
    },
    {
      entryType: EntryType.EXPENSE,
      pmName: 'Cash / Transfer',
      groupName: 'Taxis & Rideshare',
      categoryName: 'Transport',
      comment: 'Taxis & Cabify',
      transactionDate: '1/12/25',
      paymentMonthStr: 'dic-25',
      installments: 1,
      installment: 1,
      totalAmount: 24000,
    },
    {
      entryType: EntryType.EXPENSE,
      pmName: 'Visa Ciudad',
      groupName: 'Bank Fees',
      categoryName: 'Miscellaneous',
      comment: 'Comisión Liq. Y Adm. De Cuenta',
      transactionDate: '1/12/25',
      paymentMonthStr: 'dic-25',
      installments: 1,
      installment: 1,
      totalAmount: 5337.2,
    },
    {
      entryType: EntryType.EXPENSE,
      pmName: 'Visa Ciudad',
      groupName: 'Bank Fees',
      categoryName: 'Miscellaneous',
      comment: 'IVA 21%',
      transactionDate: '1/12/25',
      paymentMonthStr: 'dic-25',
      installments: 1,
      installment: 1,
      totalAmount: 1120.8,
    },
    {
      entryType: EntryType.EXPENSE,
      pmName: 'Visa Galicia',
      groupName: 'Subscriptions',
      categoryName: 'Miscellaneous',
      comment: 'Youtube Premium',
      transactionDate: '1/12/25',
      paymentMonthStr: 'dic-25',
      installments: 1,
      installment: 1,
      totalAmount: 6759.2,
    },
    {
      entryType: EntryType.EXPENSE,
      pmName: 'Visa Galicia',
      groupName: 'Subscriptions',
      categoryName: 'Miscellaneous',
      comment: 'Wordwall',
      transactionDate: '1/12/25',
      paymentMonthStr: 'dic-25',
      installments: 1,
      installment: 1,
      totalAmount: 781,
    },
    {
      entryType: EntryType.EXPENSE,
      pmName: 'Visa Galicia',
      groupName: 'Subscriptions',
      categoryName: 'Miscellaneous',
      comment: 'Wordwall - Impuestos',
      transactionDate: '1/12/25',
      paymentMonthStr: 'dic-25',
      installments: 1,
      installment: 1,
      totalAmount: 179.6,
    },
    {
      entryType: EntryType.EXPENSE,
      pmName: 'Visa Galicia',
      groupName: 'Córdoba',
      categoryName: 'Miscellaneous',
      comment: 'Pasaje Ida 24/5',
      transactionDate: '21/5/25',
      paymentMonthStr: 'dic-25',
      installments: 9,
      installment: 7,
      totalAmount: 37590.5,
    },
    {
      entryType: EntryType.EXPENSE,
      pmName: 'Cash / Transfer',
      groupName: 'Childcare',
      categoryName: 'Home Expenses',
      comment: 'Victoria',
      transactionDate: '1/12/25',
      paymentMonthStr: 'dic-25',
      installments: 1,
      installment: 1,
      totalAmount: 55957.2,
    },
    {
      entryType: EntryType.EXPENSE,
      pmName: 'Cash / Transfer',
      groupName: 'Childcare',
      categoryName: 'Home Expenses',
      comment: 'Victoria - Aguinaldo',
      transactionDate: '1/12/25',
      paymentMonthStr: 'dic-25',
      installments: 1,
      installment: 1,
      totalAmount: 30000,
    },
    {
      entryType: EntryType.EXPENSE,
      pmName: 'Visa Ciudad',
      groupName: 'Inflatable Mattress',
      categoryName: 'Home Expenses',
      comment: 'Colchón inflable',
      transactionDate: '9/1/25',
      paymentMonthStr: 'dic-25',
      installments: 12,
      installment: 11,
      totalAmount: 119999.9,
    },
    {
      entryType: EntryType.EXPENSE,
      pmName: 'Visa Ciudad',
      groupName: 'Moving',
      categoryName: 'Home Expenses',
      comment: 'Lavarropas',
      transactionDate: '30/3/25',
      paymentMonthStr: 'dic-25',
      installments: 18,
      installment: 8,
      totalAmount: 602899,
    },
    {
      entryType: EntryType.EXPENSE,
      pmName: 'Cash / Transfer',
      groupName: 'Utilities Lavalle',
      categoryName: 'Home Expenses',
      comment: 'Aysa',
      transactionDate: '1/12/25',
      paymentMonthStr: 'dic-25',
      installments: 1,
      installment: 1,
      totalAmount: 12653,
    },
    {
      entryType: EntryType.EXPENSE,
      pmName: 'Visa Galicia',
      groupName: 'Utilities Lavalle',
      categoryName: 'Home Expenses',
      comment: 'Seguro Hogar',
      transactionDate: '1/12/25',
      paymentMonthStr: 'dic-25',
      installments: 1,
      installment: 1,
      totalAmount: 22546.3,
    },
    {
      entryType: EntryType.EXPENSE,
      pmName: 'Visa Galicia',
      groupName: 'Streaming Services',
      categoryName: 'Home Expenses',
      comment: 'Spotify',
      transactionDate: '1/12/25',
      paymentMonthStr: 'dic-25',
      installments: 1,
      installment: 1,
      totalAmount: 3280.2,
    },
    {
      entryType: EntryType.EXPENSE,
      pmName: 'Visa Galicia',
      groupName: 'Streaming Services',
      categoryName: 'Home Expenses',
      comment: 'Meli+',
      transactionDate: '1/12/25',
      paymentMonthStr: 'dic-25',
      installments: 1,
      installment: 1,
      totalAmount: 12299,
    },
    {
      entryType: EntryType.EXPENSE,
      pmName: 'Visa Ciudad',
      groupName: 'Miscellaneous',
      categoryName: 'Entertainment',
      comment: 'Club La Nacion',
      transactionDate: '1/12/25',
      paymentMonthStr: 'dic-25',
      installments: 1,
      installment: 1,
      totalAmount: 5070,
    },
    {
      entryType: EntryType.EXPENSE,
      pmName: 'Visa Galicia',
      groupName: 'Streaming Services',
      categoryName: 'Home Expenses',
      comment: 'Netflix',
      transactionDate: '1/12/25',
      paymentMonthStr: 'dic-25',
      installments: 1,
      installment: 1,
      totalAmount: 18118.5,
    },
    {
      entryType: EntryType.EXPENSE,
      pmName: 'Visa Galicia',
      groupName: 'Miscellaneous',
      categoryName: 'Entertainment',
      comment: 'Clarin 365 Plus',
      transactionDate: '1/12/25',
      paymentMonthStr: 'dic-25',
      installments: 1,
      installment: 1,
      totalAmount: 5800,
    },
    {
      entryType: EntryType.EXPENSE,
      pmName: 'Visa Galicia',
      groupName: 'Childcare',
      categoryName: 'Home Expenses',
      comment: 'Victoria - Aportes',
      transactionDate: '1/12/25',
      paymentMonthStr: 'ene-26',
      installments: 1,
      installment: 1,
      totalAmount: 8072.6,
    },
    {
      entryType: EntryType.EXPENSE,
      pmName: 'Visa Galicia',
      groupName: 'Streaming Services',
      categoryName: 'Home Expenses',
      comment: 'Prime Video',
      transactionDate: '1/12/25',
      paymentMonthStr: 'dic-25',
      installments: 1,
      installment: 1,
      totalAmount: 7863.8,
    },
    {
      entryType: EntryType.EXPENSE,
      pmName: 'Visa Ciudad',
      groupName: 'Bedding',
      categoryName: 'Home Expenses',
      comment: 'Sábanas Noah y Liam',
      transactionDate: '8/8/25',
      paymentMonthStr: 'dic-25',
      installments: 10,
      installment: 4,
      totalAmount: 69980,
    },
    {
      entryType: EntryType.EXPENSE,
      pmName: 'Visa Ciudad',
      groupName: 'Gifts',
      categoryName: 'Gifts',
      comment: 'Regalos Cumple',
      transactionDate: '14/8/25',
      paymentMonthStr: 'dic-25',
      installments: 6,
      installment: 4,
      totalAmount: 7649.4,
    },
    {
      entryType: EntryType.EXPENSE,
      pmName: 'Visa Ciudad',
      groupName: 'Gifts',
      categoryName: 'Gifts',
      comment: 'Regalos Dia del Niño',
      transactionDate: '14/8/25',
      paymentMonthStr: 'dic-25',
      installments: 6,
      installment: 4,
      totalAmount: 32283,
    },
    {
      entryType: EntryType.EXPENSE,
      pmName: 'Visa Galicia',
      groupName: 'Subscriptions',
      categoryName: 'Miscellaneous',
      comment: 'Google One',
      transactionDate: '1/12/25',
      paymentMonthStr: 'dic-25',
      installments: 1,
      installment: 1,
      totalAmount: 2825.8,
    },
    {
      entryType: EntryType.EXPENSE,
      pmName: 'Visa Galicia',
      groupName: 'Subscriptions',
      categoryName: 'Miscellaneous',
      comment: 'Google One - Impuestos',
      transactionDate: '1/12/25',
      paymentMonthStr: 'dic-25',
      installments: 1,
      installment: 1,
      totalAmount: 649.9,
    },
    {
      entryType: EntryType.EXPENSE,
      pmName: 'Cash / Transfer',
      groupName: 'Therapy',
      categoryName: 'Health',
      comment: 'Terapia',
      transactionDate: '1/12/25',
      paymentMonthStr: 'dic-25',
      installments: 1,
      installment: 1,
      totalAmount: 40500,
    },
    {
      entryType: EntryType.EXPENSE,
      pmName: 'Mastercard',
      groupName: 'Bazaar',
      categoryName: 'Home Expenses',
      comment: 'Tender',
      transactionDate: '30/8/25',
      paymentMonthStr: 'dic-25',
      installments: 3,
      installment: 3,
      totalAmount: 100953,
    },
    {
      entryType: EntryType.EXPENSE,
      pmName: 'Visa Ciudad',
      groupName: 'Subscriptions',
      categoryName: 'Entertainment',
      comment: 'Rappi Pro',
      transactionDate: '1/11/25',
      paymentMonthStr: 'dic-25',
      installments: 1,
      installment: 1,
      totalAmount: 7999,
    },
    {
      entryType: EntryType.EXPENSE,
      pmName: 'Cash / Transfer',
      groupName: 'Noah Therapies',
      categoryName: 'Childcare',
      comment: 'Copago Giochi',
      transactionDate: '1/12/25',
      paymentMonthStr: 'dic-25',
      installments: 1,
      installment: 1,
      totalAmount: 25000,
    },
    {
      entryType: EntryType.EXPENSE,
      pmName: 'Visa Galicia',
      groupName: 'Gifts',
      categoryName: 'Childcare',
      comment: 'Regalos Cumple Noah',
      transactionDate: '3/9/25',
      paymentMonthStr: 'dic-25',
      installments: 3,
      installment: 3,
      totalAmount: 31997,
    },
    {
      entryType: EntryType.EXPENSE,
      pmName: 'Visa Galicia',
      groupName: 'Miscellaneous',
      categoryName: 'Miscellaneous',
      comment: 'Enchufe',
      transactionDate: '21/9/25',
      paymentMonthStr: 'dic-25',
      installments: 3,
      installment: 3,
      totalAmount: 16000,
    },
    {
      entryType: EntryType.EXPENSE,
      pmName: 'Visa Galicia',
      groupName: 'Clothing',
      categoryName: 'Clothing',
      comment: 'Jeans',
      transactionDate: '21/9/25',
      paymentMonthStr: 'dic-25',
      installments: 3,
      installment: 3,
      totalAmount: 62850,
    },
    // Supermarket / variable expenses Dec
    {
      entryType: EntryType.EXPENSE,
      pmName: 'Mastercard',
      groupName: 'Supermarket',
      categoryName: 'Home Expenses',
      comment: 'Carrefour',
      transactionDate: '27/10/25',
      paymentMonthStr: 'dic-25',
      installments: 1,
      installment: 1,
      totalAmount: 8470.7,
    },
    {
      entryType: EntryType.EXPENSE,
      pmName: 'Mastercard',
      groupName: 'Supermarket',
      categoryName: 'Home Expenses',
      comment: 'Carrefour',
      transactionDate: '6/11/25',
      paymentMonthStr: 'dic-25',
      installments: 1,
      installment: 1,
      totalAmount: 156599.7,
    },
    {
      entryType: EntryType.EXPENSE,
      pmName: 'Mastercard',
      groupName: 'Supermarket',
      categoryName: 'Home Expenses',
      comment: 'Carrefour - Descuento',
      transactionDate: '6/11/25',
      paymentMonthStr: 'dic-25',
      installments: 1,
      installment: 1,
      totalAmount: -16917,
    },
    {
      entryType: EntryType.EXPENSE,
      pmName: 'Visa Ciudad',
      groupName: 'Supermarket',
      categoryName: 'Home Expenses',
      comment: 'Coto',
      transactionDate: '23/10/25',
      paymentMonthStr: 'dic-25',
      installments: 1,
      installment: 1,
      totalAmount: 17120.4,
    },
    {
      entryType: EntryType.EXPENSE,
      pmName: 'Visa Ciudad',
      groupName: 'Delivery',
      categoryName: 'Dining Out',
      comment: 'Rappi',
      transactionDate: '23/10/25',
      paymentMonthStr: 'dic-25',
      installments: 1,
      installment: 1,
      totalAmount: 19523,
    },
    {
      entryType: EntryType.EXPENSE,
      pmName: 'Visa Ciudad',
      groupName: 'Lunches & Coffee',
      categoryName: 'Dining Out',
      comment: 'Almuerzo Colegio',
      transactionDate: '24/10/25',
      paymentMonthStr: 'dic-25',
      installments: 1,
      installment: 1,
      totalAmount: 7275.3,
    },
    {
      entryType: EntryType.EXPENSE,
      pmName: 'Visa Ciudad',
      groupName: 'Car',
      categoryName: 'Transport',
      comment: 'Estacionamiento',
      transactionDate: '24/10/25',
      paymentMonthStr: 'dic-25',
      installments: 1,
      installment: 1,
      totalAmount: 25000,
    },
    {
      entryType: EntryType.EXPENSE,
      pmName: 'Visa Ciudad',
      groupName: 'Supermarket',
      categoryName: 'Home Expenses',
      comment: 'Día',
      transactionDate: '26/10/25',
      paymentMonthStr: 'dic-25',
      installments: 1,
      installment: 1,
      totalAmount: 15545,
    },
    {
      entryType: EntryType.EXPENSE,
      pmName: 'Visa Ciudad',
      groupName: 'Car',
      categoryName: 'Transport',
      comment: 'Nafta',
      transactionDate: '26/10/25',
      paymentMonthStr: 'dic-25',
      installments: 1,
      installment: 1,
      totalAmount: 32067,
    },
    {
      entryType: EntryType.EXPENSE,
      pmName: 'Visa Ciudad',
      groupName: 'Pharmacy',
      categoryName: 'Health',
      comment: 'Farmacity',
      transactionDate: '27/10/25',
      paymentMonthStr: 'dic-25',
      installments: 1,
      installment: 1,
      totalAmount: 7877,
    },
    {
      entryType: EntryType.EXPENSE,
      pmName: 'Visa Ciudad',
      groupName: 'Kids Outings',
      categoryName: 'Dining Out',
      comment: 'McDonalds',
      transactionDate: '27/10/25',
      paymentMonthStr: 'dic-25',
      installments: 1,
      installment: 1,
      totalAmount: 8299,
    },
    {
      entryType: EntryType.EXPENSE,
      pmName: 'Visa Ciudad',
      groupName: 'Supermarket',
      categoryName: 'Home Expenses',
      comment: 'Coto',
      transactionDate: '29/10/25',
      paymentMonthStr: 'dic-25',
      installments: 1,
      installment: 1,
      totalAmount: 18011.4,
    },
    {
      entryType: EntryType.EXPENSE,
      pmName: 'Visa Ciudad',
      groupName: 'Supermarket',
      categoryName: 'Home Expenses',
      comment: 'Pañuelos de papel',
      transactionDate: '29/10/25',
      paymentMonthStr: 'dic-25',
      installments: 1,
      installment: 1,
      totalAmount: 2290,
    },
    {
      entryType: EntryType.EXPENSE,
      pmName: 'Visa Ciudad',
      groupName: 'Lunches & Coffee',
      categoryName: 'Dining Out',
      comment: 'Almuerzo Colegio',
      transactionDate: '30/10/25',
      paymentMonthStr: 'dic-25',
      installments: 1,
      installment: 1,
      totalAmount: 4500,
    },
    {
      entryType: EntryType.EXPENSE,
      pmName: 'Visa Ciudad',
      groupName: 'Supermarket',
      categoryName: 'Home Expenses',
      comment: 'Res',
      transactionDate: '8/11/25',
      paymentMonthStr: 'dic-25',
      installments: 1,
      installment: 1,
      totalAmount: 56595,
    },
    {
      entryType: EntryType.EXPENSE,
      pmName: 'Visa Ciudad',
      groupName: 'Taxis & Rideshare',
      categoryName: 'Transport',
      comment: 'Didi',
      transactionDate: '14/11/25',
      paymentMonthStr: 'dic-25',
      installments: 1,
      installment: 1,
      totalAmount: 5740,
    },
    {
      entryType: EntryType.EXPENSE,
      pmName: 'Visa Ciudad',
      groupName: 'Taxis & Rideshare',
      categoryName: 'Transport',
      comment: 'Didi',
      transactionDate: '14/11/25',
      paymentMonthStr: 'dic-25',
      installments: 1,
      installment: 1,
      totalAmount: 6770,
    },
    {
      entryType: EntryType.EXPENSE,
      pmName: 'Visa Ciudad',
      groupName: 'Taxis & Rideshare',
      categoryName: 'Transport',
      comment: 'Didi',
      transactionDate: '15/11/25',
      paymentMonthStr: 'dic-25',
      installments: 1,
      installment: 1,
      totalAmount: 7257.6,
    },
    {
      entryType: EntryType.EXPENSE,
      pmName: 'Amex Galicia',
      groupName: 'Kids Outings',
      categoryName: 'Dining Out',
      comment: 'Las Esclavas',
      transactionDate: '31/10/25',
      paymentMonthStr: 'dic-25',
      installments: 1,
      installment: 1,
      totalAmount: 6500,
    },
    {
      entryType: EntryType.EXPENSE,
      pmName: 'Amex Galicia',
      groupName: 'Kids Outings',
      categoryName: 'Dining Out',
      comment: 'Las Esclavas',
      transactionDate: '7/11/25',
      paymentMonthStr: 'dic-25',
      installments: 1,
      installment: 1,
      totalAmount: 5000,
    },
    {
      entryType: EntryType.EXPENSE,
      pmName: 'Amex Galicia',
      groupName: 'Kids Outings',
      categoryName: 'Dining Out',
      comment: 'Las Esclavas',
      transactionDate: '14/11/25',
      paymentMonthStr: 'dic-25',
      installments: 1,
      installment: 1,
      totalAmount: 4000,
    },
    {
      entryType: EntryType.EXPENSE,
      pmName: 'Visa Galicia',
      groupName: 'Birthday',
      categoryName: 'Childcare',
      comment: 'Caramelos',
      transactionDate: '31/10/25',
      paymentMonthStr: 'dic-25',
      installments: 1,
      installment: 1,
      totalAmount: 8358,
    },
    {
      entryType: EntryType.EXPENSE,
      pmName: 'Visa Galicia',
      groupName: 'Kids Outings',
      categoryName: 'Dining Out',
      comment: 'McDonalds',
      transactionDate: '31/10/25',
      paymentMonthStr: 'dic-25',
      installments: 1,
      installment: 1,
      totalAmount: 14900,
    },
    {
      entryType: EntryType.EXPENSE,
      pmName: 'Visa Galicia',
      groupName: 'Delivery',
      categoryName: 'Dining Out',
      comment: 'Rappi',
      transactionDate: '2/11/25',
      paymentMonthStr: 'dic-25',
      installments: 1,
      installment: 1,
      totalAmount: 31458.5,
    },
    {
      entryType: EntryType.EXPENSE,
      pmName: 'Visa Galicia',
      groupName: 'Delivery',
      categoryName: 'Dining Out',
      comment: 'Rappi',
      transactionDate: '2/11/25',
      paymentMonthStr: 'dic-25',
      installments: 1,
      installment: 1,
      totalAmount: 10291,
    },
    {
      entryType: EntryType.EXPENSE,
      pmName: 'Visa Galicia',
      groupName: 'Lunches & Coffee',
      categoryName: 'Dining Out',
      comment: 'Café Martínez',
      transactionDate: '4/11/25',
      paymentMonthStr: 'dic-25',
      installments: 1,
      installment: 1,
      totalAmount: 9500,
    },
    {
      entryType: EntryType.EXPENSE,
      pmName: 'Visa Galicia',
      groupName: 'Delivery',
      categoryName: 'Dining Out',
      comment: 'Rappi',
      transactionDate: '5/11/25',
      paymentMonthStr: 'dic-25',
      installments: 1,
      installment: 1,
      totalAmount: 21448,
    },
    {
      entryType: EntryType.EXPENSE,
      pmName: 'Visa Galicia',
      groupName: 'Kids Outings',
      categoryName: 'Dining Out',
      comment: 'McDonalds',
      transactionDate: '8/11/25',
      paymentMonthStr: 'dic-25',
      installments: 1,
      installment: 1,
      totalAmount: 30298,
    },
    {
      entryType: EntryType.EXPENSE,
      pmName: 'Visa Galicia',
      groupName: 'Streaming Services',
      categoryName: 'Home Expenses',
      comment: 'Spotify - Impuestos',
      transactionDate: '1/12/25',
      paymentMonthStr: 'dic-25',
      installments: 1,
      installment: 1,
      totalAmount: 797,
    },
    {
      entryType: EntryType.EXPENSE,
      pmName: 'Visa Galicia',
      groupName: 'Clothing',
      categoryName: 'Childcare',
      comment: 'Cheeky - Cuota 1',
      transactionDate: '8/11/25',
      paymentMonthStr: 'dic-25',
      installments: 9,
      installment: 1,
      totalAmount: 59850,
    },
    {
      entryType: EntryType.EXPENSE,
      pmName: 'Visa Galicia',
      groupName: 'Subscriptions',
      categoryName: 'Miscellaneous',
      comment: 'Linkedin',
      transactionDate: '1/12/25',
      paymentMonthStr: 'dic-25',
      installments: 1,
      installment: 1,
      totalAmount: 1789.2,
    },
    {
      entryType: EntryType.EXPENSE,
      pmName: 'Visa Galicia',
      groupName: 'Subscriptions',
      categoryName: 'Miscellaneous',
      comment: 'Linkedin - Impuestos',
      transactionDate: '1/12/25',
      paymentMonthStr: 'dic-25',
      installments: 1,
      installment: 1,
      totalAmount: 411.5,
    },
    {
      entryType: EntryType.EXPENSE,
      pmName: 'Visa Galicia',
      groupName: 'Supermarket',
      categoryName: 'Home Expenses',
      comment: 'Coto',
      transactionDate: '10/11/25',
      paymentMonthStr: 'dic-25',
      installments: 1,
      installment: 1,
      totalAmount: 17600.4,
    },
    {
      entryType: EntryType.EXPENSE,
      pmName: 'Visa Galicia',
      groupName: 'Supermarket',
      categoryName: 'Home Expenses',
      comment: 'Coto',
      transactionDate: '11/11/25',
      paymentMonthStr: 'dic-25',
      installments: 1,
      installment: 1,
      totalAmount: 12977.2,
    },
    {
      entryType: EntryType.EXPENSE,
      pmName: 'Visa Galicia',
      groupName: 'Gifts',
      categoryName: 'Childcare',
      comment: 'Regalos Cumple Noah',
      transactionDate: '11/11/25',
      paymentMonthStr: 'dic-25',
      installments: 3,
      installment: 1,
      totalAmount: 20398.3,
    },
    {
      entryType: EntryType.EXPENSE,
      pmName: 'Visa Galicia',
      groupName: 'Lunches & Coffee',
      categoryName: 'Dining Out',
      comment: 'Almuerzo Colegio',
      transactionDate: '13/11/25',
      paymentMonthStr: 'dic-25',
      installments: 1,
      installment: 1,
      totalAmount: 4500,
    },
    {
      entryType: EntryType.EXPENSE,
      pmName: 'Visa Galicia',
      groupName: 'Kids Outings',
      categoryName: 'Dining Out',
      comment: 'McDonalds',
      transactionDate: '16/11/25',
      paymentMonthStr: 'dic-25',
      installments: 1,
      installment: 1,
      totalAmount: 25399,
    },
    {
      entryType: EntryType.EXPENSE,
      pmName: 'Visa Galicia',
      groupName: 'Supermarket',
      categoryName: 'Home Expenses',
      comment: 'Día',
      transactionDate: '16/11/25',
      paymentMonthStr: 'dic-25',
      installments: 1,
      installment: 1,
      totalAmount: 1506,
    },
    {
      entryType: EntryType.EXPENSE,
      pmName: 'Visa Galicia',
      groupName: 'Pharmacy',
      categoryName: 'Health',
      comment: 'Remedios',
      transactionDate: '19/11/25',
      paymentMonthStr: 'dic-25',
      installments: 1,
      installment: 1,
      totalAmount: 19975,
    },
    {
      entryType: EntryType.EXPENSE,
      pmName: 'Visa Galicia',
      groupName: 'Delivery',
      categoryName: 'Dining Out',
      comment: 'Pizza',
      transactionDate: '19/11/25',
      paymentMonthStr: 'dic-25',
      installments: 1,
      installment: 1,
      totalAmount: 21800,
    },
    {
      entryType: EntryType.EXPENSE,
      pmName: 'Visa Galicia',
      groupName: 'Subscriptions',
      categoryName: 'Miscellaneous',
      comment: 'Scribd',
      transactionDate: '22/11/25',
      paymentMonthStr: 'dic-25',
      installments: 1,
      installment: 1,
      totalAmount: 14185.8,
    },
    {
      entryType: EntryType.EXPENSE,
      pmName: 'Visa Galicia',
      groupName: 'Subscriptions',
      categoryName: 'Miscellaneous',
      comment: 'Scribd - Impuestos',
      transactionDate: '22/11/25',
      paymentMonthStr: 'dic-25',
      installments: 1,
      installment: 1,
      totalAmount: 3262.7,
    },
    {
      entryType: EntryType.EXPENSE,
      pmName: 'Visa Galicia',
      groupName: 'Subscriptions',
      categoryName: 'Miscellaneous',
      comment: 'Youtube Premium - Impuestos',
      transactionDate: '1/12/25',
      paymentMonthStr: 'dic-25',
      installments: 1,
      installment: 1,
      totalAmount: 1642.2,
    },
    {
      entryType: EntryType.EXPENSE,
      pmName: 'Cash / Transfer',
      groupName: 'Liam Kindergarten',
      categoryName: 'Childcare',
      comment: 'Foto Acto',
      transactionDate: '1/12/25',
      paymentMonthStr: 'dic-25',
      installments: 1,
      installment: 1,
      totalAmount: 17000,
    },

    // ── JANUARY 2026 ─────────────────────────────────────────────────────────
    {
      entryType: EntryType.EXPENSE,
      pmName: 'Cash / Transfer',
      groupName: 'Rent & Building Fees',
      categoryName: 'Home Expenses',
      comment: 'Alquiler',
      transactionDate: '1/1/26',
      paymentMonthStr: 'ene-26',
      installments: 1,
      installment: 1,
      totalAmount: 564848,
    },
    {
      entryType: EntryType.EXPENSE,
      pmName: 'Cash / Transfer',
      groupName: 'Rent & Building Fees',
      categoryName: 'Home Expenses',
      comment: 'Expensas',
      transactionDate: '1/1/26',
      paymentMonthStr: 'ene-26',
      installments: 1,
      installment: 1,
      totalAmount: 120297,
    },
    {
      entryType: EntryType.EXPENSE,
      pmName: 'Cash / Transfer',
      groupName: 'Utilities Lavalle',
      categoryName: 'Home Expenses',
      comment: 'ABL',
      transactionDate: '1/1/26',
      paymentMonthStr: 'ene-26',
      installments: 1,
      installment: 1,
      totalAmount: 19489,
    },
    {
      entryType: EntryType.EXPENSE,
      pmName: 'Cash / Transfer',
      groupName: 'Utilities Lavalle',
      categoryName: 'Home Expenses',
      comment: 'Aysa',
      transactionDate: '1/1/26',
      paymentMonthStr: 'ene-26',
      installments: 1,
      installment: 1,
      totalAmount: 11410,
    },
    {
      entryType: EntryType.EXPENSE,
      pmName: 'Cash / Transfer',
      groupName: 'Childcare',
      categoryName: 'Home Expenses',
      comment: 'Yamile',
      transactionDate: '1/1/26',
      paymentMonthStr: 'ene-26',
      installments: 1,
      installment: 1,
      totalAmount: 97036,
    },
    {
      entryType: EntryType.EXPENSE,
      pmName: 'Visa Galicia',
      groupName: 'Childcare',
      categoryName: 'Home Expenses',
      comment: 'Yamile - Aportes',
      transactionDate: '1/1/26',
      paymentMonthStr: 'ene-26',
      installments: 1,
      installment: 1,
      totalAmount: 33904.2,
    },
    {
      entryType: EntryType.EXPENSE,
      pmName: 'Cash / Transfer',
      groupName: 'Childcare',
      categoryName: 'Home Expenses',
      comment: 'Victoria',
      transactionDate: '1/1/26',
      paymentMonthStr: 'ene-26',
      installments: 1,
      installment: 1,
      totalAmount: 31200,
    },
    {
      entryType: EntryType.EXPENSE,
      pmName: 'Cash / Transfer',
      groupName: 'Therapy',
      categoryName: 'Health',
      comment: 'Terapia',
      transactionDate: '1/1/26',
      paymentMonthStr: 'ene-26',
      installments: 1,
      installment: 1,
      totalAmount: 32400,
    },
    {
      entryType: EntryType.EXPENSE,
      pmName: 'Visa Galicia',
      groupName: 'Health Insurance',
      categoryName: 'Health',
      comment: 'OSDE 11/2025',
      transactionDate: '1/1/26',
      paymentMonthStr: 'ene-26',
      installments: 1,
      installment: 1,
      totalAmount: 351872.8,
    },
    {
      entryType: EntryType.EXPENSE,
      pmName: 'Visa Galicia',
      groupName: 'Utilities Lavalle',
      categoryName: 'Home Expenses',
      comment: 'Edesur',
      transactionDate: '1/1/26',
      paymentMonthStr: 'ene-26',
      installments: 1,
      installment: 1,
      totalAmount: 16567,
    },
    {
      entryType: EntryType.EXPENSE,
      pmName: 'Visa Ciudad',
      groupName: 'Utilities Lavalle',
      categoryName: 'Home Expenses',
      comment: 'Metrogas',
      transactionDate: '1/1/26',
      paymentMonthStr: 'ene-26',
      installments: 1,
      installment: 1,
      totalAmount: 12783.9,
    },
    {
      entryType: EntryType.EXPENSE,
      pmName: 'Visa Galicia',
      groupName: 'Utilities Lavalle',
      categoryName: 'Home Expenses',
      comment: 'Cable/Internet',
      transactionDate: '1/1/26',
      paymentMonthStr: 'ene-26',
      installments: 1,
      installment: 1,
      totalAmount: 25232,
    },
    {
      entryType: EntryType.EXPENSE,
      pmName: 'Visa Galicia',
      groupName: 'Utilities',
      categoryName: 'Home Expenses',
      comment: 'Celular Mati',
      transactionDate: '1/1/26',
      paymentMonthStr: 'ene-26',
      installments: 1,
      installment: 1,
      totalAmount: 40723.5,
    },
    {
      entryType: EntryType.EXPENSE,
      pmName: 'Visa Galicia',
      groupName: 'Utilities Lavalle',
      categoryName: 'Home Expenses',
      comment: 'Seguro Hogar',
      transactionDate: '1/1/26',
      paymentMonthStr: 'ene-26',
      installments: 1,
      installment: 1,
      totalAmount: 23109.6,
    },
    {
      entryType: EntryType.EXPENSE,
      pmName: 'Visa Ciudad',
      groupName: 'Bank Fees',
      categoryName: 'Miscellaneous',
      comment: 'Comisión Liq. Y Adm. De Cuenta',
      transactionDate: '1/1/26',
      paymentMonthStr: 'ene-26',
      installments: 1,
      installment: 1,
      totalAmount: 5337.2,
    },
    {
      entryType: EntryType.EXPENSE,
      pmName: 'Visa Ciudad',
      groupName: 'Bank Fees',
      categoryName: 'Miscellaneous',
      comment: 'IVA 21%',
      transactionDate: '1/1/26',
      paymentMonthStr: 'ene-26',
      installments: 1,
      installment: 1,
      totalAmount: 1120.8,
    },
    {
      entryType: EntryType.EXPENSE,
      pmName: 'Visa Ciudad',
      groupName: 'Inflatable Mattress',
      categoryName: 'Home Expenses',
      comment: 'Colchón inflable',
      transactionDate: '9/1/25',
      paymentMonthStr: 'ene-26',
      installments: 12,
      installment: 12,
      totalAmount: 119999.9,
    },
    {
      entryType: EntryType.EXPENSE,
      pmName: 'Visa Ciudad',
      groupName: 'Moving',
      categoryName: 'Home Expenses',
      comment: 'Lavarropas',
      transactionDate: '30/3/25',
      paymentMonthStr: 'ene-26',
      installments: 18,
      installment: 9,
      totalAmount: 602899,
    },
    {
      entryType: EntryType.EXPENSE,
      pmName: 'Visa Ciudad',
      groupName: 'Miscellaneous',
      categoryName: 'Entertainment',
      comment: 'Club La Nacion',
      transactionDate: '1/1/26',
      paymentMonthStr: 'ene-26',
      installments: 1,
      installment: 1,
      totalAmount: 16900,
    },
    {
      entryType: EntryType.EXPENSE,
      pmName: 'Visa Ciudad',
      groupName: 'Bedding',
      categoryName: 'Home Expenses',
      comment: 'Sábanas Noah y Liam',
      transactionDate: '8/8/25',
      paymentMonthStr: 'ene-26',
      installments: 10,
      installment: 5,
      totalAmount: 69980,
    },
    {
      entryType: EntryType.EXPENSE,
      pmName: 'Visa Ciudad',
      groupName: 'Gifts',
      categoryName: 'Gifts',
      comment: 'Regalos Cumple',
      transactionDate: '14/8/25',
      paymentMonthStr: 'ene-26',
      installments: 6,
      installment: 5,
      totalAmount: 7649.4,
    },
    {
      entryType: EntryType.EXPENSE,
      pmName: 'Visa Ciudad',
      groupName: 'Gifts',
      categoryName: 'Gifts',
      comment: 'Regalos Dia del Niño',
      transactionDate: '14/8/25',
      paymentMonthStr: 'ene-26',
      installments: 6,
      installment: 5,
      totalAmount: 32283,
    },
    {
      entryType: EntryType.EXPENSE,
      pmName: 'Visa Galicia',
      groupName: 'Streaming Services',
      categoryName: 'Home Expenses',
      comment: 'Spotify',
      transactionDate: '1/1/26',
      paymentMonthStr: 'ene-26',
      installments: 1,
      installment: 1,
      totalAmount: 3412.1,
    },
    {
      entryType: EntryType.EXPENSE,
      pmName: 'Visa Galicia',
      groupName: 'Streaming Services',
      categoryName: 'Home Expenses',
      comment: 'Prime Video',
      transactionDate: '1/1/26',
      paymentMonthStr: 'ene-26',
      installments: 1,
      installment: 1,
      totalAmount: 7863,
    },
    {
      entryType: EntryType.EXPENSE,
      pmName: 'Visa Galicia',
      groupName: 'Streaming Services',
      categoryName: 'Home Expenses',
      comment: 'Netflix',
      transactionDate: '1/1/26',
      paymentMonthStr: 'ene-26',
      installments: 1,
      installment: 1,
      totalAmount: 15570.5,
    },
    {
      entryType: EntryType.EXPENSE,
      pmName: 'Visa Galicia',
      groupName: 'Streaming Services',
      categoryName: 'Home Expenses',
      comment: 'Meli+',
      transactionDate: '1/1/26',
      paymentMonthStr: 'ene-26',
      installments: 1,
      installment: 1,
      totalAmount: 12299,
    },
    {
      entryType: EntryType.EXPENSE,
      pmName: 'Visa Galicia',
      groupName: 'Subscriptions',
      categoryName: 'Miscellaneous',
      comment: 'Youtube Premium',
      transactionDate: '1/1/26',
      paymentMonthStr: 'ene-26',
      installments: 1,
      installment: 1,
      totalAmount: 7062.6,
    },
    {
      entryType: EntryType.EXPENSE,
      pmName: 'Visa Galicia',
      groupName: 'Subscriptions',
      categoryName: 'Miscellaneous',
      comment: 'Google One',
      transactionDate: '1/1/26',
      paymentMonthStr: 'ene-26',
      installments: 1,
      installment: 1,
      totalAmount: 2965.1,
    },
    {
      entryType: EntryType.EXPENSE,
      pmName: 'Visa Galicia',
      groupName: 'Córdoba',
      categoryName: 'Miscellaneous',
      comment: 'Pasaje Ida 24/5',
      transactionDate: '21/5/25',
      paymentMonthStr: 'ene-26',
      installments: 9,
      installment: 8,
      totalAmount: 37590.5,
    },
    {
      entryType: EntryType.EXPENSE,
      pmName: 'Visa Galicia',
      groupName: 'Gifts',
      categoryName: 'Childcare',
      comment: 'Regalos Cumple Noah',
      transactionDate: '11/11/25',
      paymentMonthStr: 'ene-26',
      installments: 3,
      installment: 2,
      totalAmount: 20398.3,
    },
    {
      entryType: EntryType.EXPENSE,
      pmName: 'Visa Galicia',
      groupName: 'Clothing',
      categoryName: 'Childcare',
      comment: 'Cheeky - Cuota 2',
      transactionDate: '8/11/25',
      paymentMonthStr: 'ene-26',
      installments: 9,
      installment: 2,
      totalAmount: 59850,
    },
    {
      entryType: EntryType.EXPENSE,
      pmName: 'Visa Galicia',
      groupName: 'Miscellaneous',
      categoryName: 'Entertainment',
      comment: 'Clarin 365 Plus',
      transactionDate: '1/1/26',
      paymentMonthStr: 'ene-26',
      installments: 1,
      installment: 1,
      totalAmount: 5800,
    },
    {
      entryType: EntryType.EXPENSE,
      pmName: 'Visa Galicia',
      groupName: 'Subscriptions',
      categoryName: 'Miscellaneous',
      comment: 'Wordawall',
      transactionDate: '1/1/26',
      paymentMonthStr: 'ene-26',
      installments: 1,
      installment: 1,
      totalAmount: 834.4,
    },
    {
      entryType: EntryType.EXPENSE,
      pmName: 'Visa Galicia',
      groupName: 'Subscriptions',
      categoryName: 'Miscellaneous',
      comment: 'Linkedin',
      transactionDate: '1/1/26',
      paymentMonthStr: 'ene-26',
      installments: 1,
      installment: 1,
      totalAmount: 1877.4,
    },
    {
      entryType: EntryType.EXPENSE,
      pmName: 'Visa Galicia',
      groupName: 'Bank Fees',
      categoryName: 'Miscellaneous',
      comment: 'Impuestos',
      transactionDate: '1/1/26',
      paymentMonthStr: 'ene-26',
      installments: 1,
      installment: 1,
      totalAmount: 15236.5,
    },
    {
      entryType: EntryType.EXPENSE,
      pmName: 'Visa Galicia',
      groupName: 'Bank Fees',
      categoryName: 'Miscellaneous',
      comment: 'Impuestos - Devolución',
      transactionDate: '1/1/26',
      paymentMonthStr: 'ene-26',
      installments: 1,
      installment: 1,
      totalAmount: -10390.3,
    },
    // Jan variable
    {
      entryType: EntryType.EXPENSE,
      pmName: 'Amex Galicia',
      groupName: 'Kids Outings',
      categoryName: 'Dining Out',
      comment: 'Las Esclavas',
      transactionDate: '28/11/25',
      paymentMonthStr: 'ene-26',
      installments: 1,
      installment: 1,
      totalAmount: 6100,
    },
    {
      entryType: EntryType.EXPENSE,
      pmName: 'Amex Galicia',
      groupName: 'Kids Outings',
      categoryName: 'Dining Out',
      comment: 'Las Esclavas',
      transactionDate: '19/12/25',
      paymentMonthStr: 'ene-26',
      installments: 1,
      installment: 1,
      totalAmount: 21700,
    },
    {
      entryType: EntryType.EXPENSE,
      pmName: 'Visa Galicia',
      groupName: 'Supermarket',
      categoryName: 'Home Expenses',
      comment: 'Vedulería',
      transactionDate: '28/11/25',
      paymentMonthStr: 'ene-26',
      installments: 1,
      installment: 1,
      totalAmount: 17118.4,
    },
    {
      entryType: EntryType.EXPENSE,
      pmName: 'Visa Galicia',
      groupName: 'Lunches & Coffee',
      categoryName: 'Dining Out',
      comment: 'Mostaza',
      transactionDate: '30/11/25',
      paymentMonthStr: 'ene-26',
      installments: 1,
      installment: 1,
      totalAmount: 19090,
    },
    {
      entryType: EntryType.EXPENSE,
      pmName: 'Visa Galicia',
      groupName: 'Supermarket',
      categoryName: 'Home Expenses',
      comment: 'Día',
      transactionDate: '30/11/25',
      paymentMonthStr: 'ene-26',
      installments: 1,
      installment: 1,
      totalAmount: 16467.6,
    },
    {
      entryType: EntryType.EXPENSE,
      pmName: 'Visa Galicia',
      groupName: 'Childcare',
      categoryName: 'Home Expenses',
      comment: 'Victoria - Aportes',
      transactionDate: '1/12/25',
      paymentMonthStr: 'ene-26',
      installments: 1,
      installment: 1,
      totalAmount: 8235.4,
    },
    {
      entryType: EntryType.EXPENSE,
      pmName: 'Visa Galicia',
      groupName: 'Noah School',
      categoryName: 'Childcare',
      comment: 'Vianda',
      transactionDate: '2/12/25',
      paymentMonthStr: 'ene-26',
      installments: 1,
      installment: 1,
      totalAmount: 14400,
    },
    {
      entryType: EntryType.EXPENSE,
      pmName: 'Visa Galicia',
      groupName: 'Delivery',
      categoryName: 'Dining Out',
      comment: 'Rappi',
      transactionDate: '5/12/25',
      paymentMonthStr: 'ene-26',
      installments: 1,
      installment: 1,
      totalAmount: 5558,
    },
    {
      entryType: EntryType.EXPENSE,
      pmName: 'Visa Galicia',
      groupName: 'Supermarket',
      categoryName: 'Home Expenses',
      comment: 'Día',
      transactionDate: '7/12/25',
      paymentMonthStr: 'ene-26',
      installments: 1,
      installment: 1,
      totalAmount: 27827,
    },
    {
      entryType: EntryType.EXPENSE,
      pmName: 'Visa Galicia',
      groupName: 'Delivery',
      categoryName: 'Dining Out',
      comment: 'Rappi',
      transactionDate: '7/12/25',
      paymentMonthStr: 'ene-26',
      installments: 1,
      installment: 1,
      totalAmount: 21278,
    },
    {
      entryType: EntryType.EXPENSE,
      pmName: 'Visa Galicia',
      groupName: 'Supermarket',
      categoryName: 'Home Expenses',
      comment: 'Coto',
      transactionDate: '8/12/25',
      paymentMonthStr: 'ene-26',
      installments: 1,
      installment: 1,
      totalAmount: 14612.3,
    },
    {
      entryType: EntryType.EXPENSE,
      pmName: 'Visa Galicia',
      groupName: 'Gifts',
      categoryName: 'Childcare',
      comment: 'Regalos Cumple Noah',
      transactionDate: '8/12/25',
      paymentMonthStr: 'ene-26',
      installments: 3,
      installment: 1,
      totalAmount: 9999,
    },
    {
      entryType: EntryType.EXPENSE,
      pmName: 'Visa Galicia',
      groupName: 'Lunches & Coffee',
      categoryName: 'Dining Out',
      comment: "Wendy's",
      transactionDate: '8/12/25',
      paymentMonthStr: 'ene-26',
      installments: 1,
      installment: 1,
      totalAmount: 17800,
    },
    {
      entryType: EntryType.EXPENSE,
      pmName: 'Visa Galicia',
      groupName: 'Dining with Friends',
      categoryName: 'Dining Out',
      comment: 'El Fortín',
      transactionDate: '9/12/25',
      paymentMonthStr: 'ene-26',
      installments: 1,
      installment: 1,
      totalAmount: 80200,
    },
    {
      entryType: EntryType.EXPENSE,
      pmName: 'Visa Galicia',
      groupName: 'Noah Kindergarten',
      categoryName: 'Childcare',
      comment: 'Matricula',
      transactionDate: '10/12/25',
      paymentMonthStr: 'ene-26',
      installments: 1,
      installment: 1,
      totalAmount: 575000,
    },
    {
      entryType: EntryType.EXPENSE,
      pmName: 'Visa Galicia',
      groupName: 'Lunches & Coffee',
      categoryName: 'Dining Out',
      comment: 'Almuerzo Colegio',
      transactionDate: '11/12/25',
      paymentMonthStr: 'ene-26',
      installments: 1,
      installment: 1,
      totalAmount: 6419.4,
    },
    {
      entryType: EntryType.EXPENSE,
      pmName: 'Visa Galicia',
      groupName: 'Kids Outings',
      categoryName: 'Dining Out',
      comment: 'McDonalds',
      transactionDate: '13/12/25',
      paymentMonthStr: 'ene-26',
      installments: 1,
      installment: 1,
      totalAmount: 27200,
    },
    {
      entryType: EntryType.EXPENSE,
      pmName: 'Visa Galicia',
      groupName: 'Supermarket',
      categoryName: 'Home Expenses',
      comment: 'Coto',
      transactionDate: '14/12/25',
      paymentMonthStr: 'ene-26',
      installments: 1,
      installment: 1,
      totalAmount: 46279.7,
    },
    {
      entryType: EntryType.EXPENSE,
      pmName: 'Visa Galicia',
      groupName: 'Kids Outings',
      categoryName: 'Dining Out',
      comment: 'Café Martínez',
      transactionDate: '15/12/25',
      paymentMonthStr: 'ene-26',
      installments: 1,
      installment: 1,
      totalAmount: 28500,
    },
    {
      entryType: EntryType.EXPENSE,
      pmName: 'Visa Galicia',
      groupName: 'Kids Outings',
      categoryName: 'Dining Out',
      comment: 'Helado',
      transactionDate: '17/12/25',
      paymentMonthStr: 'ene-26',
      installments: 1,
      installment: 1,
      totalAmount: 5000,
    },
    {
      entryType: EntryType.EXPENSE,
      pmName: 'Visa Galicia',
      groupName: 'Supermarket',
      categoryName: 'Home Expenses',
      comment: 'Día',
      transactionDate: '17/12/25',
      paymentMonthStr: 'ene-26',
      installments: 1,
      installment: 1,
      totalAmount: 5966.7,
    },
    {
      entryType: EntryType.EXPENSE,
      pmName: 'Visa Galicia',
      groupName: 'Lunches & Coffee',
      categoryName: 'Dining Out',
      comment: 'Desayuno',
      transactionDate: '18/12/25',
      paymentMonthStr: 'ene-26',
      installments: 1,
      installment: 1,
      totalAmount: 3500,
    },
    {
      entryType: EntryType.EXPENSE,
      pmName: 'Visa Galicia',
      groupName: 'Kids Outings',
      categoryName: 'Dining Out',
      comment: 'McDonalds',
      transactionDate: '20/12/25',
      paymentMonthStr: 'ene-26',
      installments: 1,
      installment: 1,
      totalAmount: 27900,
    },
    {
      entryType: EntryType.EXPENSE,
      pmName: 'Visa Galicia',
      groupName: 'Supermarket',
      categoryName: 'Home Expenses',
      comment: 'Día',
      transactionDate: '20/12/25',
      paymentMonthStr: 'ene-26',
      installments: 1,
      installment: 1,
      totalAmount: 10625,
    },
    {
      entryType: EntryType.EXPENSE,
      pmName: 'Visa Galicia',
      groupName: 'Outing with Sofi',
      categoryName: 'Dining Out',
      comment: 'KFC',
      transactionDate: '21/12/25',
      paymentMonthStr: 'ene-26',
      installments: 1,
      installment: 1,
      totalAmount: 14400,
    },
    {
      entryType: EntryType.EXPENSE,
      pmName: 'Visa Galicia',
      groupName: 'Outing with Sofi',
      categoryName: 'Transport',
      comment: 'Estacionamiento',
      transactionDate: '21/12/25',
      paymentMonthStr: 'ene-26',
      installments: 1,
      installment: 1,
      totalAmount: 9450,
    },
    {
      entryType: EntryType.EXPENSE,
      pmName: 'Visa Galicia',
      groupName: 'Outing with Sofi',
      categoryName: 'Dining Out',
      comment: 'Bebidas',
      transactionDate: '21/12/25',
      paymentMonthStr: 'ene-26',
      installments: 1,
      installment: 1,
      totalAmount: 4200,
    },
    {
      entryType: EntryType.EXPENSE,
      pmName: 'Visa Galicia',
      groupName: 'Clothing',
      categoryName: 'Childcare',
      comment: 'Zapatillas Noah - Cuota 1',
      transactionDate: '22/12/25',
      paymentMonthStr: 'ene-26',
      installments: 9,
      installment: 1,
      totalAmount: 49999.3,
    },
    {
      entryType: EntryType.EXPENSE,
      pmName: 'Visa Galicia',
      groupName: 'Kids Outings',
      categoryName: 'Dining Out',
      comment: 'Helado',
      transactionDate: '22/12/25',
      paymentMonthStr: 'ene-26',
      installments: 1,
      installment: 1,
      totalAmount: 3980,
    },
    {
      entryType: EntryType.EXPENSE,
      pmName: 'Visa Galicia',
      groupName: 'Kids Outings',
      categoryName: 'Dining Out',
      comment: 'Desayuno',
      transactionDate: '22/12/25',
      paymentMonthStr: 'ene-26',
      installments: 1,
      installment: 1,
      totalAmount: 4100,
    },
    {
      entryType: EntryType.EXPENSE,
      pmName: 'Visa Galicia',
      groupName: 'Kids Outings',
      categoryName: 'Dining Out',
      comment: 'Desayuno',
      transactionDate: '23/12/25',
      paymentMonthStr: 'ene-26',
      installments: 1,
      installment: 1,
      totalAmount: 21800,
    },
    {
      entryType: EntryType.EXPENSE,
      pmName: 'Visa Galicia',
      groupName: 'Kids Outings',
      categoryName: 'Dining Out',
      comment: 'Churros',
      transactionDate: '23/12/25',
      paymentMonthStr: 'ene-26',
      installments: 1,
      installment: 1,
      totalAmount: 7500,
    },
    {
      entryType: EntryType.EXPENSE,
      pmName: 'Visa Galicia',
      groupName: 'Footwear',
      categoryName: 'Clothing',
      comment: 'Alpargatas',
      transactionDate: '23/12/25',
      paymentMonthStr: 'ene-26',
      installments: 1,
      installment: 1,
      totalAmount: 28000,
    },
    {
      entryType: EntryType.EXPENSE,
      pmName: 'Mastercard',
      groupName: 'Supermarket',
      categoryName: 'Home Expenses',
      comment: 'Carrefour',
      transactionDate: '21/11/25',
      paymentMonthStr: 'ene-26',
      installments: 1,
      installment: 1,
      totalAmount: 205159.3,
    },
    {
      entryType: EntryType.EXPENSE,
      pmName: 'Mastercard',
      groupName: 'Supermarket',
      categoryName: 'Home Expenses',
      comment: 'Carrefour',
      transactionDate: '15/12/25',
      paymentMonthStr: 'ene-26',
      installments: 1,
      installment: 1,
      totalAmount: 10304,
    },
    {
      entryType: EntryType.EXPENSE,
      pmName: 'Mastercard',
      groupName: 'Supermarket',
      categoryName: 'Home Expenses',
      comment: 'Carrefour',
      transactionDate: '21/12/25',
      paymentMonthStr: 'ene-26',
      installments: 1,
      installment: 1,
      totalAmount: 8130.6,
    },
    {
      entryType: EntryType.EXPENSE,
      pmName: 'Visa Ciudad',
      groupName: 'Delivery',
      categoryName: 'Dining Out',
      comment: 'Pedidos Ya',
      transactionDate: '21/11/25',
      paymentMonthStr: 'ene-26',
      installments: 1,
      installment: 1,
      totalAmount: 27664,
    },
    {
      entryType: EntryType.EXPENSE,
      pmName: 'Visa Ciudad',
      groupName: 'Supermarket',
      categoryName: 'Home Expenses',
      comment: 'Pañales',
      transactionDate: '21/11/25',
      paymentMonthStr: 'ene-26',
      installments: 1,
      installment: 1,
      totalAmount: 99200,
    },
    {
      entryType: EntryType.EXPENSE,
      pmName: 'Visa Ciudad',
      groupName: 'Supermarket',
      categoryName: 'Home Expenses',
      comment: 'Día',
      transactionDate: '24/11/25',
      paymentMonthStr: 'ene-26',
      installments: 1,
      installment: 1,
      totalAmount: 17627.5,
    },
    {
      entryType: EntryType.EXPENSE,
      pmName: 'Visa Ciudad',
      groupName: 'Supermarket',
      categoryName: 'Home Expenses',
      comment: 'Grido',
      transactionDate: '26/11/25',
      paymentMonthStr: 'ene-26',
      installments: 1,
      installment: 1,
      totalAmount: 23000,
    },
    {
      entryType: EntryType.EXPENSE,
      pmName: 'Visa Ciudad',
      groupName: 'Lunches & Coffee',
      categoryName: 'Dining Out',
      comment: 'Almuerzo Colegio',
      transactionDate: '27/11/25',
      paymentMonthStr: 'ene-26',
      installments: 1,
      installment: 1,
      totalAmount: 4500,
    },
    {
      entryType: EntryType.EXPENSE,
      pmName: 'Visa Ciudad',
      groupName: 'Taxis & Rideshare',
      categoryName: 'Transport',
      comment: 'Didi',
      transactionDate: '29/11/25',
      paymentMonthStr: 'ene-26',
      installments: 1,
      installment: 1,
      totalAmount: 9700,
    },
    {
      entryType: EntryType.EXPENSE,
      pmName: 'Visa Ciudad',
      groupName: 'Supermarket',
      categoryName: 'Home Expenses',
      comment: 'El Puente',
      transactionDate: '1/12/25',
      paymentMonthStr: 'ene-26',
      installments: 1,
      installment: 1,
      totalAmount: 12077.9,
    },
    {
      entryType: EntryType.EXPENSE,
      pmName: 'Visa Ciudad',
      groupName: 'Kids Outings',
      categoryName: 'Dining Out',
      comment: 'Desayuno',
      transactionDate: '14/12/25',
      paymentMonthStr: 'ene-26',
      installments: 1,
      installment: 1,
      totalAmount: 9350,
    },
    {
      entryType: EntryType.EXPENSE,
      pmName: 'Visa Ciudad',
      groupName: 'Subscriptions',
      categoryName: 'Entertainment',
      comment: 'Rappi Pro',
      transactionDate: '1/1/26',
      paymentMonthStr: 'ene-26',
      installments: 1,
      installment: 1,
      totalAmount: 9990,
    },
    {
      entryType: EntryType.EXPENSE,
      pmName: 'Visa Ciudad',
      groupName: 'Supermarket',
      categoryName: 'Home Expenses',
      comment: 'Res',
      transactionDate: '20/12/25',
      paymentMonthStr: 'ene-26',
      installments: 1,
      installment: 1,
      totalAmount: 19453,
    },
    {
      entryType: EntryType.EXPENSE,
      pmName: 'Visa Ciudad',
      groupName: 'Bank Fees',
      categoryName: 'Miscellaneous',
      comment: 'Devolución',
      transactionDate: '4/12/25',
      paymentMonthStr: 'ene-26',
      installments: 1,
      installment: 1,
      totalAmount: -8439,
    },
    {
      entryType: EntryType.EXPENSE,
      pmName: 'Cash / Transfer',
      groupName: 'Pool',
      categoryName: 'Entertainment',
      comment: 'Bebidas',
      transactionDate: '2/1/26',
      paymentMonthStr: 'ene-26',
      installments: 1,
      installment: 1,
      totalAmount: 14000,
    },
    {
      entryType: EntryType.EXPENSE,
      pmName: 'Cash / Transfer',
      groupName: 'Farm',
      categoryName: 'Entertainment',
      comment: 'Entradas',
      transactionDate: '3/1/26',
      paymentMonthStr: 'ene-26',
      installments: 1,
      installment: 1,
      totalAmount: 34000,
    },
    {
      entryType: EntryType.EXPENSE,
      pmName: 'Cash / Transfer',
      groupName: 'Farm',
      categoryName: 'Entertainment',
      comment: 'Bebidas',
      transactionDate: '3/1/26',
      paymentMonthStr: 'ene-26',
      installments: 1,
      installment: 1,
      totalAmount: 7500,
    },
    {
      entryType: EntryType.EXPENSE,
      pmName: 'Cash / Transfer',
      groupName: 'Car',
      categoryName: 'Transport',
      comment: 'Lavadero',
      transactionDate: '4/1/26',
      paymentMonthStr: 'ene-26',
      installments: 1,
      installment: 1,
      totalAmount: 20000,
    },
    {
      entryType: EntryType.EXPENSE,
      pmName: 'Cash / Transfer',
      groupName: 'Hairdresser',
      categoryName: 'Childcare',
      comment: 'Corte Liam',
      transactionDate: '7/1/26',
      paymentMonthStr: 'ene-26',
      installments: 1,
      installment: 1,
      totalAmount: 16000,
    },
    {
      entryType: EntryType.EXPENSE,
      pmName: 'Cash / Transfer',
      groupName: 'Summer Vacation',
      categoryName: 'Entertainment',
      comment: 'Calesita',
      transactionDate: '9/1/26',
      paymentMonthStr: 'ene-26',
      installments: 1,
      installment: 1,
      totalAmount: 6500,
    },
    {
      entryType: EntryType.EXPENSE,
      pmName: 'Cash / Transfer',
      groupName: 'Lunches & Coffee',
      categoryName: 'Dining Out',
      comment: 'Starbucks - Devolución',
      transactionDate: '20/1/26',
      paymentMonthStr: 'ene-26',
      installments: 1,
      installment: 1,
      totalAmount: -3800,
    },
    {
      entryType: EntryType.EXPENSE,
      pmName: 'Cash / Transfer',
      groupName: 'Miscellaneous',
      categoryName: 'Home Expenses',
      comment: 'Tv Stick - Devolución',
      transactionDate: '14/1/26',
      paymentMonthStr: 'ene-26',
      installments: 1,
      installment: 1,
      totalAmount: -126000,
    },

    // ── FEBRUARY 2026 ────────────────────────────────────────────────────────
    {
      entryType: EntryType.EXPENSE,
      pmName: 'Cash / Transfer',
      groupName: 'Rent & Building Fees',
      categoryName: 'Home Expenses',
      comment: 'Alquiler',
      transactionDate: '1/2/26',
      paymentMonthStr: 'feb-26',
      installments: 1,
      installment: 1,
      totalAmount: 564848,
    },
    {
      entryType: EntryType.EXPENSE,
      pmName: 'Cash / Transfer',
      groupName: 'Rent & Building Fees',
      categoryName: 'Home Expenses',
      comment: 'Expensas',
      transactionDate: '1/2/26',
      paymentMonthStr: 'feb-26',
      installments: 1,
      installment: 1,
      totalAmount: 123817,
    },
    {
      entryType: EntryType.EXPENSE,
      pmName: 'Cash / Transfer',
      groupName: 'Utilities Lavalle',
      categoryName: 'Home Expenses',
      comment: 'ABL',
      transactionDate: '1/2/26',
      paymentMonthStr: 'feb-26',
      installments: 1,
      installment: 1,
      totalAmount: 20071,
    },
    {
      entryType: EntryType.EXPENSE,
      pmName: 'Cash / Transfer',
      groupName: 'Utilities Lavalle',
      categoryName: 'Home Expenses',
      comment: 'Aysa',
      transactionDate: '1/2/26',
      paymentMonthStr: 'feb-26',
      installments: 1,
      installment: 1,
      totalAmount: 11410,
    },
    {
      entryType: EntryType.EXPENSE,
      pmName: 'Cash / Transfer',
      groupName: 'Childcare',
      categoryName: 'Home Expenses',
      comment: 'Yamile',
      transactionDate: '1/2/26',
      paymentMonthStr: 'feb-26',
      installments: 1,
      installment: 1,
      totalAmount: 234750,
    },
    {
      entryType: EntryType.EXPENSE,
      pmName: 'Visa Galicia',
      groupName: 'Childcare',
      categoryName: 'Home Expenses',
      comment: 'Yamile - Aportes',
      transactionDate: '1/2/26',
      paymentMonthStr: 'feb-26',
      installments: 1,
      installment: 1,
      totalAmount: 34037,
    },
    {
      entryType: EntryType.EXPENSE,
      pmName: 'Cash / Transfer',
      groupName: 'Therapy',
      categoryName: 'Health',
      comment: 'Terapia',
      transactionDate: '1/2/26',
      paymentMonthStr: 'feb-26',
      installments: 1,
      installment: 1,
      totalAmount: 17000,
    },
    {
      entryType: EntryType.EXPENSE,
      pmName: 'Cash / Transfer',
      groupName: 'Noah Therapies',
      categoryName: 'Childcare',
      comment: 'Copago Giochi',
      transactionDate: '1/2/26',
      paymentMonthStr: 'feb-26',
      installments: 1,
      installment: 1,
      totalAmount: 61765.3,
    },
    {
      entryType: EntryType.EXPENSE,
      pmName: 'Visa Galicia',
      groupName: 'Health Insurance',
      categoryName: 'Health',
      comment: 'OSDE 12/2025',
      transactionDate: '1/2/26',
      paymentMonthStr: 'feb-26',
      installments: 1,
      installment: 1,
      totalAmount: 215603.1,
    },
    {
      entryType: EntryType.EXPENSE,
      pmName: 'Visa Galicia',
      groupName: 'Utilities Lavalle',
      categoryName: 'Home Expenses',
      comment: 'Edesur',
      transactionDate: '1/2/26',
      paymentMonthStr: 'feb-26',
      installments: 1,
      installment: 1,
      totalAmount: 29349.9,
    },
    {
      entryType: EntryType.EXPENSE,
      pmName: 'Visa Ciudad',
      groupName: 'Utilities Lavalle',
      categoryName: 'Home Expenses',
      comment: 'Metrogas',
      transactionDate: '1/2/26',
      paymentMonthStr: 'feb-26',
      installments: 1,
      installment: 1,
      totalAmount: 12423.5,
    },
    {
      entryType: EntryType.EXPENSE,
      pmName: 'Visa Galicia',
      groupName: 'Utilities Lavalle',
      categoryName: 'Home Expenses',
      comment: 'Cable/Internet',
      transactionDate: '1/2/26',
      paymentMonthStr: 'feb-26',
      installments: 1,
      installment: 1,
      totalAmount: 26099.6,
    },
    {
      entryType: EntryType.EXPENSE,
      pmName: 'Visa Galicia',
      groupName: 'Utilities',
      categoryName: 'Home Expenses',
      comment: 'Celular Mati',
      transactionDate: '1/2/26',
      paymentMonthStr: 'feb-26',
      installments: 1,
      installment: 1,
      totalAmount: 41930.5,
    },
    {
      entryType: EntryType.EXPENSE,
      pmName: 'Visa Galicia',
      groupName: 'Utilities Lavalle',
      categoryName: 'Home Expenses',
      comment: 'Seguro Hogar',
      transactionDate: '1/2/26',
      paymentMonthStr: 'feb-26',
      installments: 1,
      installment: 1,
      totalAmount: 23627.1,
    },
    {
      entryType: EntryType.EXPENSE,
      pmName: 'Visa Ciudad',
      groupName: 'Bank Fees',
      categoryName: 'Miscellaneous',
      comment: 'Comisión Liq. Y Adm. De Cuenta',
      transactionDate: '1/2/26',
      paymentMonthStr: 'feb-26',
      installments: 1,
      installment: 1,
      totalAmount: 5337.2,
    },
    {
      entryType: EntryType.EXPENSE,
      pmName: 'Visa Ciudad',
      groupName: 'Bank Fees',
      categoryName: 'Miscellaneous',
      comment: 'IVA 21%',
      transactionDate: '1/2/26',
      paymentMonthStr: 'feb-26',
      installments: 1,
      installment: 1,
      totalAmount: 1120.8,
    },
    {
      entryType: EntryType.EXPENSE,
      pmName: 'Visa Ciudad',
      groupName: 'Bank Fees',
      categoryName: 'Miscellaneous',
      comment: 'Percepciones',
      transactionDate: '1/2/26',
      paymentMonthStr: 'feb-26',
      installments: 1,
      installment: 1,
      totalAmount: 23800.7,
    },
    {
      entryType: EntryType.EXPENSE,
      pmName: 'Visa Ciudad',
      groupName: 'Moving',
      categoryName: 'Home Expenses',
      comment: 'Lavarropas',
      transactionDate: '30/3/25',
      paymentMonthStr: 'feb-26',
      installments: 18,
      installment: 10,
      totalAmount: 602899,
    },
    {
      entryType: EntryType.EXPENSE,
      pmName: 'Visa Ciudad',
      groupName: 'Miscellaneous',
      categoryName: 'Entertainment',
      comment: 'Club La Nacion',
      transactionDate: '1/2/26',
      paymentMonthStr: 'feb-26',
      installments: 1,
      installment: 1,
      totalAmount: 5070,
    },
    {
      entryType: EntryType.EXPENSE,
      pmName: 'Visa Ciudad',
      groupName: 'Bedding',
      categoryName: 'Home Expenses',
      comment: 'Sábanas Noah y Liam',
      transactionDate: '8/8/25',
      paymentMonthStr: 'feb-26',
      installments: 10,
      installment: 6,
      totalAmount: 69980,
    },
    {
      entryType: EntryType.EXPENSE,
      pmName: 'Visa Ciudad',
      groupName: 'Gifts',
      categoryName: 'Gifts',
      comment: 'Regalos Cumple',
      transactionDate: '14/8/25',
      paymentMonthStr: 'feb-26',
      installments: 6,
      installment: 6,
      totalAmount: 7649.4,
    },
    {
      entryType: EntryType.EXPENSE,
      pmName: 'Visa Ciudad',
      groupName: 'Gifts',
      categoryName: 'Gifts',
      comment: 'Regalos Dia del Niño',
      transactionDate: '14/8/25',
      paymentMonthStr: 'feb-26',
      installments: 6,
      installment: 6,
      totalAmount: 32283,
    },
    {
      entryType: EntryType.EXPENSE,
      pmName: 'Visa Ciudad',
      groupName: 'Miscellaneous',
      categoryName: 'Miscellaneous',
      comment: 'Soporte Auto',
      transactionDate: '26/12/25',
      paymentMonthStr: 'feb-26',
      installments: 1,
      installment: 1,
      totalAmount: 18519,
    },
    {
      entryType: EntryType.EXPENSE,
      pmName: 'Visa Ciudad',
      groupName: 'Uruguay',
      categoryName: 'Miscellaneous',
      comment: 'Almuerzo Uruguay',
      transactionDate: '28/12/25',
      paymentMonthStr: 'feb-26',
      installments: 1,
      installment: 1,
      totalAmount: 22905.2,
    },
    {
      entryType: EntryType.EXPENSE,
      pmName: 'Visa Ciudad',
      groupName: 'Uruguay',
      categoryName: 'Miscellaneous',
      comment: 'Helado Uruguay',
      transactionDate: '28/12/25',
      paymentMonthStr: 'feb-26',
      installments: 1,
      installment: 1,
      totalAmount: 2612.4,
    },
    {
      entryType: EntryType.EXPENSE,
      pmName: 'Visa Ciudad',
      groupName: 'Uruguay',
      categoryName: 'Miscellaneous',
      comment: 'Tienda Inglesa',
      transactionDate: '28/12/25',
      paymentMonthStr: 'feb-26',
      installments: 1,
      installment: 1,
      totalAmount: 54527.9,
    },
    {
      entryType: EntryType.EXPENSE,
      pmName: 'Visa Ciudad',
      groupName: 'Supermarket',
      categoryName: 'Home Expenses',
      comment: 'Día',
      transactionDate: '30/12/25',
      paymentMonthStr: 'feb-26',
      installments: 1,
      installment: 1,
      totalAmount: 7960,
    },
    {
      entryType: EntryType.EXPENSE,
      pmName: 'Visa Ciudad',
      groupName: 'Footwear',
      categoryName: 'Childcare',
      comment: 'Zapatillas Liam',
      transactionDate: '30/12/25',
      paymentMonthStr: 'feb-26',
      installments: 6,
      installment: 1,
      totalAmount: 24999,
    },
    {
      entryType: EntryType.EXPENSE,
      pmName: 'Visa Ciudad',
      groupName: 'Kids Outings',
      categoryName: 'Entertainment',
      comment: 'Playland',
      transactionDate: '30/12/25',
      paymentMonthStr: 'feb-26',
      installments: 1,
      installment: 1,
      totalAmount: 7000,
    },
    {
      entryType: EntryType.EXPENSE,
      pmName: 'Visa Ciudad',
      groupName: 'Sofi Car',
      categoryName: 'Transport',
      comment: 'Nafta',
      transactionDate: '4/1/26',
      paymentMonthStr: 'feb-26',
      installments: 1,
      installment: 1,
      totalAmount: 50009,
    },
    {
      entryType: EntryType.EXPENSE,
      pmName: 'Visa Ciudad',
      groupName: 'Taxis & Rideshare',
      categoryName: 'Transport',
      comment: 'Didi',
      transactionDate: '17/1/26',
      paymentMonthStr: 'feb-26',
      installments: 1,
      installment: 1,
      totalAmount: 6140,
    },
    {
      entryType: EntryType.EXPENSE,
      pmName: 'Visa Galicia',
      groupName: 'Streaming Services',
      categoryName: 'Home Expenses',
      comment: 'Spotify',
      transactionDate: '1/2/26',
      paymentMonthStr: 'feb-26',
      installments: 1,
      installment: 1,
      totalAmount: 3290.7,
    },
    {
      entryType: EntryType.EXPENSE,
      pmName: 'Visa Galicia',
      groupName: 'Streaming Services',
      categoryName: 'Home Expenses',
      comment: 'Prime Video',
      transactionDate: '1/2/26',
      paymentMonthStr: 'feb-26',
      installments: 1,
      installment: 1,
      totalAmount: 7863,
    },
    {
      entryType: EntryType.EXPENSE,
      pmName: 'Visa Galicia',
      groupName: 'Streaming Services',
      categoryName: 'Home Expenses',
      comment: 'Netflix',
      transactionDate: '1/2/26',
      paymentMonthStr: 'feb-26',
      installments: 1,
      installment: 1,
      totalAmount: 15270.1,
    },
    {
      entryType: EntryType.EXPENSE,
      pmName: 'Visa Galicia',
      groupName: 'Streaming Services',
      categoryName: 'Home Expenses',
      comment: 'Meli+',
      transactionDate: '1/2/26',
      paymentMonthStr: 'feb-26',
      installments: 1,
      installment: 1,
      totalAmount: 12299,
    },
    {
      entryType: EntryType.EXPENSE,
      pmName: 'Visa Galicia',
      groupName: 'Streaming Services',
      categoryName: 'Home Expenses',
      comment: 'HBO',
      transactionDate: '1/2/26',
      paymentMonthStr: 'feb-26',
      installments: 1,
      installment: 1,
      totalAmount: 7105.7,
    },
    {
      entryType: EntryType.EXPENSE,
      pmName: 'Visa Galicia',
      groupName: 'Subscriptions',
      categoryName: 'Miscellaneous',
      comment: 'Youtube Premium',
      transactionDate: '1/2/26',
      paymentMonthStr: 'feb-26',
      installments: 1,
      installment: 1,
      totalAmount: 6913.4,
    },
    {
      entryType: EntryType.EXPENSE,
      pmName: 'Visa Galicia',
      groupName: 'Subscriptions',
      categoryName: 'Miscellaneous',
      comment: 'Google One',
      transactionDate: '1/2/26',
      paymentMonthStr: 'feb-26',
      installments: 1,
      installment: 1,
      totalAmount: 2872.2,
    },
    {
      entryType: EntryType.EXPENSE,
      pmName: 'Visa Galicia',
      groupName: 'Subscriptions',
      categoryName: 'Miscellaneous',
      comment: 'Linkedin',
      transactionDate: '1/2/26',
      paymentMonthStr: 'feb-26',
      installments: 1,
      installment: 1,
      totalAmount: 1818.6,
    },
    {
      entryType: EntryType.EXPENSE,
      pmName: 'Visa Galicia',
      groupName: 'Subscriptions',
      categoryName: 'Miscellaneous',
      comment: 'Wordawall',
      transactionDate: '1/2/26',
      paymentMonthStr: 'feb-26',
      installments: 1,
      installment: 1,
      totalAmount: 808.2,
    },
    {
      entryType: EntryType.EXPENSE,
      pmName: 'Visa Galicia',
      groupName: 'Córdoba',
      categoryName: 'Miscellaneous',
      comment: 'Pasaje Ida 24/5',
      transactionDate: '21/5/25',
      paymentMonthStr: 'feb-26',
      installments: 9,
      installment: 9,
      totalAmount: 37590.5,
    },
    {
      entryType: EntryType.EXPENSE,
      pmName: 'Visa Galicia',
      groupName: 'Gifts',
      categoryName: 'Childcare',
      comment: 'Regalos Cumple Noah',
      transactionDate: '11/11/25',
      paymentMonthStr: 'feb-26',
      installments: 3,
      installment: 3,
      totalAmount: 20398.3,
    },
    {
      entryType: EntryType.EXPENSE,
      pmName: 'Visa Galicia',
      groupName: 'Gifts',
      categoryName: 'Childcare',
      comment: 'Regalos Cumple Noah',
      transactionDate: '8/12/25',
      paymentMonthStr: 'feb-26',
      installments: 3,
      installment: 2,
      totalAmount: 9999,
    },
    {
      entryType: EntryType.EXPENSE,
      pmName: 'Visa Galicia',
      groupName: 'Clothing',
      categoryName: 'Childcare',
      comment: 'Cheeky - Cuota 3',
      transactionDate: '8/11/25',
      paymentMonthStr: 'feb-26',
      installments: 9,
      installment: 3,
      totalAmount: 59850,
    },
    {
      entryType: EntryType.EXPENSE,
      pmName: 'Visa Galicia',
      groupName: 'Clothing',
      categoryName: 'Childcare',
      comment: 'Zapatillas Noah - Cuota 2',
      transactionDate: '22/12/25',
      paymentMonthStr: 'feb-26',
      installments: 9,
      installment: 2,
      totalAmount: 49999.3,
    },
    {
      entryType: EntryType.EXPENSE,
      pmName: 'Visa Galicia',
      groupName: 'Miscellaneous',
      categoryName: 'Entertainment',
      comment: 'Clarin 365 Plus',
      transactionDate: '1/2/26',
      paymentMonthStr: 'feb-26',
      installments: 1,
      installment: 1,
      totalAmount: 5800,
    },
    {
      entryType: EntryType.EXPENSE,
      pmName: 'Visa Galicia',
      groupName: 'Bank Fees',
      categoryName: 'Miscellaneous',
      comment: 'Impuestos',
      transactionDate: '1/2/26',
      paymentMonthStr: 'feb-26',
      installments: 1,
      installment: 1,
      totalAmount: 22330.8,
    },
    {
      entryType: EntryType.EXPENSE,
      pmName: 'Visa Galicia',
      groupName: 'Bank Fees',
      categoryName: 'Miscellaneous',
      comment: 'Impuestos - Devolución',
      transactionDate: '1/2/26',
      paymentMonthStr: 'feb-26',
      installments: 1,
      installment: 1,
      totalAmount: -8289.1,
    },
    {
      entryType: EntryType.EXPENSE,
      pmName: 'Mastercard',
      groupName: 'Supermarket',
      categoryName: 'Home Expenses',
      comment: 'Carrefour',
      transactionDate: '29/12/25',
      paymentMonthStr: 'feb-26',
      installments: 3,
      installment: 1,
      totalAmount: 40551.1,
    },
    {
      entryType: EntryType.EXPENSE,
      pmName: 'Mastercard',
      groupName: 'Clothing',
      categoryName: 'Clothing',
      comment: 'Ropa interior',
      transactionDate: '30/12/25',
      paymentMonthStr: 'feb-26',
      installments: 3,
      installment: 1,
      totalAmount: 36960,
    },
    {
      entryType: EntryType.EXPENSE,
      pmName: 'Mastercard',
      groupName: 'Supermarket',
      categoryName: 'Home Expenses',
      comment: 'Carrefour',
      transactionDate: '3/1/26',
      paymentMonthStr: 'feb-26',
      installments: 2,
      installment: 1,
      totalAmount: 6315.5,
    },
    {
      entryType: EntryType.EXPENSE,
      pmName: 'Mastercard',
      groupName: 'Supermarket',
      categoryName: 'Home Expenses',
      comment: 'Carrefour',
      transactionDate: '30/12/25',
      paymentMonthStr: 'feb-26',
      installments: 1,
      installment: 1,
      totalAmount: 190526.1,
    },
    {
      entryType: EntryType.EXPENSE,
      pmName: 'Mastercard',
      groupName: 'Supermarket',
      categoryName: 'Home Expenses',
      comment: 'Carrefour',
      transactionDate: '13/1/26',
      paymentMonthStr: 'feb-26',
      installments: 1,
      installment: 1,
      totalAmount: 37992.4,
    },
    {
      entryType: EntryType.EXPENSE,
      pmName: 'Mastercard',
      groupName: 'Supermarket',
      categoryName: 'Home Expenses',
      comment: 'Carrefour',
      transactionDate: '13/1/26',
      paymentMonthStr: 'feb-26',
      installments: 1,
      installment: 1,
      totalAmount: 80028.8,
    },
    {
      entryType: EntryType.EXPENSE,
      pmName: 'Visa Galicia',
      groupName: 'Summer Vacation',
      categoryName: 'Dining Out',
      comment: 'McDonalds',
      transactionDate: '30/12/25',
      paymentMonthStr: 'feb-26',
      installments: 1,
      installment: 1,
      totalAmount: 10500,
    },
    {
      entryType: EntryType.EXPENSE,
      pmName: 'Visa Galicia',
      groupName: 'Summer Vacation',
      categoryName: 'Dining Out',
      comment: 'McDonalds',
      transactionDate: '1/1/26',
      paymentMonthStr: 'feb-26',
      installments: 1,
      installment: 1,
      totalAmount: 25598,
    },
    {
      entryType: EntryType.EXPENSE,
      pmName: 'Visa Galicia',
      groupName: 'Family Snack Outing',
      categoryName: 'Dining Out',
      comment: 'Pedidos Ya',
      transactionDate: '1/1/26',
      paymentMonthStr: 'feb-26',
      installments: 1,
      installment: 1,
      totalAmount: 12199,
    },
    {
      entryType: EntryType.EXPENSE,
      pmName: 'Visa Galicia',
      groupName: 'Summer Vacation',
      categoryName: 'Entertainment',
      comment: 'Entrada Club',
      transactionDate: '2/1/26',
      paymentMonthStr: 'feb-26',
      installments: 1,
      installment: 1,
      totalAmount: 24000,
    },
    {
      entryType: EntryType.EXPENSE,
      pmName: 'Visa Galicia',
      groupName: 'Summer Vacation',
      categoryName: 'Entertainment',
      comment: 'Entrada Pileta',
      transactionDate: '2/1/26',
      paymentMonthStr: 'feb-26',
      installments: 1,
      installment: 1,
      totalAmount: 13500,
    },
    {
      entryType: EntryType.EXPENSE,
      pmName: 'Visa Galicia',
      groupName: 'Supermarket',
      categoryName: 'Home Expenses',
      comment: 'Coto',
      transactionDate: '2/1/26',
      paymentMonthStr: 'feb-26',
      installments: 1,
      installment: 1,
      totalAmount: 24778.6,
    },
    {
      entryType: EntryType.EXPENSE,
      pmName: 'Visa Galicia',
      groupName: 'Childcare',
      categoryName: 'Home Expenses',
      comment: 'Victoria - Aportes',
      transactionDate: '5/1/26',
      paymentMonthStr: 'feb-26',
      installments: 1,
      installment: 1,
      totalAmount: 8359.5,
    },
    {
      entryType: EntryType.EXPENSE,
      pmName: 'Visa Galicia',
      groupName: 'Family Outings',
      categoryName: 'Dining Out',
      comment: 'Heladería',
      transactionDate: '5/1/26',
      paymentMonthStr: 'feb-26',
      installments: 1,
      installment: 1,
      totalAmount: 18000,
    },
    {
      entryType: EntryType.EXPENSE,
      pmName: 'Visa Galicia',
      groupName: 'Lunches & Coffee',
      categoryName: 'Dining Out',
      comment: 'Mostaza',
      transactionDate: '6/1/26',
      paymentMonthStr: 'feb-26',
      installments: 1,
      installment: 1,
      totalAmount: 4490,
    },
    {
      entryType: EntryType.EXPENSE,
      pmName: 'Visa Galicia',
      groupName: 'Summer Vacation',
      categoryName: 'Dining Out',
      comment: 'McDonalds',
      transactionDate: '7/1/26',
      paymentMonthStr: 'feb-26',
      installments: 1,
      installment: 1,
      totalAmount: 36699,
    },
    {
      entryType: EntryType.EXPENSE,
      pmName: 'Visa Galicia',
      groupName: 'Summer Vacation',
      categoryName: 'Dining Out',
      comment: 'McDonalds',
      transactionDate: '7/1/26',
      paymentMonthStr: 'feb-26',
      installments: 1,
      installment: 1,
      totalAmount: 4899,
    },
    {
      entryType: EntryType.EXPENSE,
      pmName: 'Visa Galicia',
      groupName: 'Summer Vacation',
      categoryName: 'Dining Out',
      comment: 'McDonalds',
      transactionDate: '8/1/26',
      paymentMonthStr: 'feb-26',
      installments: 1,
      installment: 1,
      totalAmount: 25099,
    },
    {
      entryType: EntryType.EXPENSE,
      pmName: 'Visa Galicia',
      groupName: 'Summer Vacation',
      categoryName: 'Dining Out',
      comment: 'Guapaletas',
      transactionDate: '8/1/26',
      paymentMonthStr: 'feb-26',
      installments: 1,
      installment: 1,
      totalAmount: 13500,
    },
    {
      entryType: EntryType.EXPENSE,
      pmName: 'Visa Galicia',
      groupName: 'Summer Vacation',
      categoryName: 'Entertainment',
      comment: 'Museo de los Niños',
      transactionDate: '8/1/26',
      paymentMonthStr: 'feb-26',
      installments: 1,
      installment: 1,
      totalAmount: 15000,
    },
    {
      entryType: EntryType.EXPENSE,
      pmName: 'Visa Galicia',
      groupName: 'Miscellaneous',
      categoryName: 'Home Expenses',
      comment: 'Tv Stick',
      transactionDate: '14/1/26',
      paymentMonthStr: 'feb-26',
      installments: 6,
      installment: 1,
      totalAmount: 49999.2,
    },
    {
      entryType: EntryType.EXPENSE,
      pmName: 'Visa Galicia',
      groupName: 'Delivery',
      categoryName: 'Dining Out',
      comment: 'Sushi',
      transactionDate: '11/1/26',
      paymentMonthStr: 'feb-26',
      installments: 1,
      installment: 1,
      totalAmount: 19909,
    },
    {
      entryType: EntryType.EXPENSE,
      pmName: 'Visa Galicia',
      groupName: 'Delivery',
      categoryName: 'Dining Out',
      comment: 'Helado',
      transactionDate: '11/1/26',
      paymentMonthStr: 'feb-26',
      installments: 1,
      installment: 1,
      totalAmount: 3500,
    },
    {
      entryType: EntryType.EXPENSE,
      pmName: 'Amex Galicia',
      groupName: 'Summer Vacation',
      categoryName: 'Dining Out',
      comment: 'Las Exclavas',
      transactionDate: '9/1/26',
      paymentMonthStr: 'feb-26',
      installments: 1,
      installment: 1,
      totalAmount: 19100,
    },
    {
      entryType: EntryType.EXPENSE,
      pmName: 'Amex Galicia',
      groupName: 'Summer Vacation',
      categoryName: 'Dining Out',
      comment: 'Las Exclavas',
      transactionDate: '19/1/26',
      paymentMonthStr: 'feb-26',
      installments: 1,
      installment: 1,
      totalAmount: 15000,
    },
    {
      entryType: EntryType.EXPENSE,
      pmName: 'Visa Galicia',
      groupName: 'Supermarket',
      categoryName: 'Home Expenses',
      comment: 'Perfumeria',
      transactionDate: '12/1/26',
      paymentMonthStr: 'feb-26',
      installments: 1,
      installment: 1,
      totalAmount: 4581.6,
    },
    {
      entryType: EntryType.EXPENSE,
      pmName: 'Visa Galicia',
      groupName: 'Supermarket',
      categoryName: 'Home Expenses',
      comment: 'Eco Fresh',
      transactionDate: '14/1/26',
      paymentMonthStr: 'feb-26',
      installments: 1,
      installment: 1,
      totalAmount: 6700,
    },
    {
      entryType: EntryType.EXPENSE,
      pmName: 'Visa Galicia',
      groupName: 'Bookstore',
      categoryName: 'Home Expenses',
      comment: 'Corprint',
      transactionDate: '14/1/26',
      paymentMonthStr: 'feb-26',
      installments: 1,
      installment: 1,
      totalAmount: 1300,
    },
    {
      entryType: EntryType.EXPENSE,
      pmName: 'Visa Galicia',
      groupName: 'Summer Vacation',
      categoryName: 'Dining Out',
      comment: 'McDonalds',
      transactionDate: '16/1/26',
      paymentMonthStr: 'feb-26',
      installments: 1,
      installment: 1,
      totalAmount: 28199,
    },
    {
      entryType: EntryType.EXPENSE,
      pmName: 'Visa Galicia',
      groupName: 'Summer Vacation',
      categoryName: 'Dining Out',
      comment: 'Heladería',
      transactionDate: '16/1/26',
      paymentMonthStr: 'feb-26',
      installments: 1,
      installment: 1,
      totalAmount: 5400,
    },
    {
      entryType: EntryType.EXPENSE,
      pmName: 'Visa Galicia',
      groupName: 'Supermarket',
      categoryName: 'Home Expenses',
      comment: 'Carrefour',
      transactionDate: '17/1/26',
      paymentMonthStr: 'feb-26',
      installments: 1,
      installment: 1,
      totalAmount: 2690,
    },
    {
      entryType: EntryType.EXPENSE,
      pmName: 'Visa Galicia',
      groupName: 'Summer Vacation',
      categoryName: 'Entertainment',
      comment: 'Parque Norte',
      transactionDate: '17/1/26',
      paymentMonthStr: 'feb-26',
      installments: 1,
      installment: 1,
      totalAmount: 44000,
    },
    {
      entryType: EntryType.EXPENSE,
      pmName: 'Visa Galicia',
      groupName: 'Supermarket',
      categoryName: 'Home Expenses',
      comment: 'Vacalin',
      transactionDate: '17/1/26',
      paymentMonthStr: 'feb-26',
      installments: 1,
      installment: 1,
      totalAmount: 12060,
    },
    {
      entryType: EntryType.EXPENSE,
      pmName: 'Visa Galicia',
      groupName: 'Supermarket',
      categoryName: 'Home Expenses',
      comment: 'Jumbo',
      transactionDate: '18/1/26',
      paymentMonthStr: 'feb-26',
      installments: 1,
      installment: 1,
      totalAmount: 30609.9,
    },
    {
      entryType: EntryType.EXPENSE,
      pmName: 'Visa Galicia',
      groupName: 'Summer Vacation',
      categoryName: 'Dining Out',
      comment: 'McDonalds',
      transactionDate: '19/1/26',
      paymentMonthStr: 'feb-26',
      installments: 1,
      installment: 1,
      totalAmount: 4600,
    },
    {
      entryType: EntryType.EXPENSE,
      pmName: 'Visa Galicia',
      groupName: 'Lunches & Coffee',
      categoryName: 'Dining Out',
      comment: 'Coca',
      transactionDate: '20/1/26',
      paymentMonthStr: 'feb-26',
      installments: 1,
      installment: 1,
      totalAmount: 2465,
    },
    {
      entryType: EntryType.EXPENSE,
      pmName: 'Visa Galicia',
      groupName: 'Lunches & Coffee',
      categoryName: 'Dining Out',
      comment: 'Starbucks',
      transactionDate: '20/1/26',
      paymentMonthStr: 'feb-26',
      installments: 1,
      installment: 1,
      totalAmount: 9500,
    },
    {
      entryType: EntryType.EXPENSE,
      pmName: 'Visa Galicia',
      groupName: 'Supermarket',
      categoryName: 'Home Expenses',
      comment: 'Jumbo - Devolución',
      transactionDate: '20/1/26',
      paymentMonthStr: 'feb-26',
      installments: 1,
      installment: 1,
      totalAmount: -11262.9,
    },
    {
      entryType: EntryType.EXPENSE,
      pmName: 'Cash / Transfer',
      groupName: 'Hardware Store',
      categoryName: 'Home Expenses',
      comment: 'Ferretería',
      transactionDate: '1/2/26',
      paymentMonthStr: 'feb-26',
      installments: 1,
      installment: 1,
      totalAmount: 20073.3,
    },
  ];

  // ─── Insert transactions ──────────────────────────────────────────────────

  for (const tx of txDefs) {
    const groupId = await group(tx.groupName);
    const monthlyAmount = tx.totalAmount / tx.installments;

    // Determine status based on paymentMonth
    const pmDate = paymentMonth(tx.paymentMonthStr);
    const now = new Date();
    const currentPeriod = new Date(now.getFullYear(), now.getMonth(), 1);
    let status: Status;
    if (pmDate < currentPeriod) status = Status.CLOSED;
    else if (pmDate.getTime() === currentPeriod.getTime())
      status = Status.CURRENT;
    else status = Status.FUTURE;

    await prisma.transaction.create({
      data: {
        entryType: tx.entryType,
        status,
        transactionDate: d(tx.transactionDate),
        paymentMonth: pmDate,
        currency: Currency.ARS,
        totalAmount: tx.totalAmount,
        monthlyAmount,
        installments: tx.installments,
        installment: tx.installment,
        isPaid: status === Status.CLOSED,
        impactsCashflow: true,
        comment: tx.comment,
        transactionType: tx.transactionType ?? TransactionType.VARIABLE,
        ledgerId: ledger.id,
        categoryId: cat(tx.categoryName),
        paymentMethodId: pm(tx.pmName),
        groupId,
      },
    });
  }

  console.log(`  ✔ Transactions seeded (${txDefs.length} records)`);
};
